### PR TITLE
fix(scan_input): use event listener does not get dropped, so we do it manually

### LINKED ISSUE #147: ScanInput callback is called multiple times
After the merge of #139, particularly at https://github.com/strichliste-rs/strichliste-rs/pull/139/files#diff-fb748d4eef48d0e31b49d1cad1e952bb5678d24a204b703946049a530c049777L112-L127 , the scan input callback get's triggered multiple times.

I don't know why, but it seems like the scan_input get's registered multiple times:

In `scan_input.rs`
```rust
    let tmp = Utc::now()
    ...
    console_log(&format!("created handle: {tmp}"));

    on_cleanup(move || {
        console_log(&format!("removed handle: {tmp}"));
        handle.remove();
    });

```

Console output
```
# initial page load
created handle: 2025-11-09 02:01:35.152 UTC -- fine, but never actually get's cleaned up

# clicked on user
created handle: 2025-11-09 02:01:36.802 UTC -- wtf
removed handle: 2025-11-09 02:01:36.802 UTC  -- wtf
created handle: 2025-11-09 02:01:36.902 UTC  -- fine

# returned to homepage
created handle: 2025-11-09 02:01:38.985 UTC --fine
removed handle: 2025-11-09 02:01:36.902 UTC -- fine
```

### PR DESCRIPTION
**Pull request by DestinyofYeet**
closes #147

### CODE REVIEW

File: src/frontend/shared/scaninput_manager.rs [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+        window_event_listener, Effect, Get, ReadSignal, ReadUntracked, RwSignal, UpdateUntracked,
+        Write,
+    },
+};
+use leptos_router::hooks::use_url;
+use reactive_stores::Store;
+
+use crate::frontend::model::scaninput_manager::{Entry, ScanInputManager};
+
+const SECONDS_UNTIL_INPUT_CLEARED: u8 = 30;
```
Comment (haennes) [inline src/frontend/shared/scaninput_manager.rs]: can you move this to the struct def (see for why below)

File: src/frontend/component/scan_input.rs [hunk 2]
```diff
@@ -1,10 +1,15 @@
 use chrono::Utc;
-use leptos::{ev, prelude::*};
+use leptos::{ev::keypress, prelude::*};
+use leptos_use::{use_document, use_event_listener};
 
 const SECONDS_UNTIL_INPUT_CLEARED: i64 = 30;
 
 #[component]
-pub fn scan_input<F>(ignore_input_signals: Vec<RwSignal<bool>>, callback: F) -> impl IntoView
+pub fn scan_input<F>(
```
[the remark this answers is not in the document]
Comment (DestinyofYeet) [reply src/frontend/component/scan_input.rs]: fixed

File: src/frontend/model/scaninput_manager.rs [hunk 3]
```diff
@@ -0,0 +1,21 @@
+use leptos::prelude::WindowListenerHandle;
+
+pub const SECONDS_UNTIL_INPUT_CLEARED: u8 = 30;
+
+pub struct ScanInputManager {
```
Comment (haennes) [inline src/frontend/model/scaninput_manager.rs]: Could this also just be a vec which we check for emptyness?

**Comment by haennes** [comment]
Can you also amend the suggested changes to the respective commits instead :)

File: src/frontend/model/scaninput_manager.rs (hunk 3 above)
Comment (DestinyofYeet) [reply src/frontend/model/scaninput_manager.rs]: Well technically the option is only there, because `WindowListenerHandle`.remove() requires a owned value, so I'm abusing `Option`.take() to get an owned value out ouf a `&mut`.

**Comment by haennes** [comment]
looks good will merge
